name: "lenet5"
n_classes: 10
input_shape: [1, 28, 28]
layers:
  - backbone:
    - type: ConvBlock
      params:
        in_channels: 1
        out_channels: 6
        kernel_size: 5
        stride: 1
        padding: 0
    - type: ConvBlock
      params:
        in_channels: 6
        out_channels: 16
        kernel_size: 5
        stride: 1
        padding: 0
  - head:
    - type: Flatten
    - type: Linear
      params:
        in_features: 400
        out_features: 120
    - type: ReLU
    - type: Linear
      params:
        in_features: 120
        out_features: 84
    - type: ReLU
    - type: Linear
      params:
        in_features: 84
        out_features: 10
        activation: null
    - type: ReLU

